# Generated by Django 3.2.5 on 2022-02-22 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de mise ajour')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('username', models.CharField(max_length=250, unique=True, verbose_name="Nom d'utilisateur")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse mail')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom Complet')),
                ('adress', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, help_text='22891025263', max_length=11, null=True, unique=True)),
                ('auth_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="Code d'authentification")),
                ('profile', models.ImageField(blank=True, null=True, upload_to='User/Profile', verbose_name='Avatar de profil')),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de mise ajour')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Libelle')),
                ('nbr_sms', models.IntegerField(blank=True, null=True, verbose_name='Nombre de messages')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Prix')),
                ('tarif', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tarif')),
                ('is_actif', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de mise ajour')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date de souscription')),
                ('nbr_sms_sent', models.IntegerField(blank=True, null=True, verbose_name='Nombre de sms envoyé')),
                ('nbr_sms_rem', models.IntegerField(blank=True, null=True, verbose_name='Nombre de sms restant')),
                ('to_be_payed', models.IntegerField(blank=True, null=True, verbose_name='A payer')),
                ('is_payed', models.BooleanField(blank=True, default=True, null=True)),
                ('is_actif', models.BooleanField(blank=True, default=True, null=True)),
                ('tag', models.IntegerField(blank=True, choices=[(1, 'BASIC'), (3, 'BRONZE'), (5, 'SILVER'), (7, 'GOLD'), (10, 'DIAMOND'), (0, 'NO LIMIT')], default=1, null=True)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='souscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='apiwassa.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de mise ajour')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('sender', models.CharField(blank=True, max_length=250, null=True, verbose_name='Entete')),
                ('receptor', models.CharField(blank=True, max_length=250, null=True, verbose_name='Numero du recepteur')),
                ('text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Texte')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'envoie")),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Delivré'), (2, 'Echoué'), (3, 'En Attente')], null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de mise ajour')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Libelle du payement')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Nombre de sms restant')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date de souscription')),
                ('payed', models.BooleanField(blank=True, default=False, null=True)),
                ('souscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payements', to='apiwassa.souscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de mise ajour')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('entete', models.CharField(blank=True, max_length=250, null=True, verbose_name='Entete des SMS')),
                ('is_default', models.BooleanField(blank=True, null=True)),
                ('is_actif', models.BooleanField(blank=True, default=False, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
