# Generated by Django 3.2.5 on 2022-02-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiwassa', '0004_auto_20220222_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='auth_code',
            field=models.IntegerField(blank=True, default=13501, null=True, verbose_name="Code d'authentification"),
        ),
        migrations.AlterField(
            model_name='souscription',
            name='numero',
            field=models.IntegerField(blank=True, default=688321, null=True),
        ),
    ]
